export const LIMITE_MINIMO_CARACTERES_MENSAGEM = 15;
export const LIMITE_MAXIMO_CARACTERES_MENSAGEM = 150;
export const LIMITE_MAXIMO_CARACTERES_REPETIDOS_SEQUENCIA = 5;
export const DURACAO_PADRAO_PARTIDA_SEGUNDOS = 180;
export const DURACAO_PADRAO_VEREDITO_SEGUNDOS = 15;
export const COOLDOWN_PADRAO_SEGUNDOS = 3;
export const ORCAMENTO_PADRAO_INTERLOCUTOR = 3000;
